### ISSUE TITLE
V4L2loopback doesn't show on webcam list

### ISSUE THREAD

**Issue by madovsky** [i-rinat/freshplayerplugin#304]
I don't know if it comes from Flash Player, V4L2loopback or freshwrapper,
but the author of V4L2loopback use his module with flash player without problem
here is the thread he's explained how to test V4L2loopback
https://github.com/umlaeute/v4l2loopback/issues/64

**Comment by i-rinat** [comment]
I scan `/dev/v4l/by-path` directory to enumerate all existing webcams in the system. It looks like that directory is filled by udev scripts at runtime, but only for USB webcams. So freshwrapper don't know that there is additional v4l device.

I traced NPAPI Flash, and it uses entries in `/sys/class/video4linux` to find all devices. I think I should use that technique too.

**Comment by madovsky** [comment]
Great if there is a solution for that. thanks

**Comment by i-rinat** [comment]
7bcd1de6607e51f179a84991448695f1c46726f8 should fix this

**Comment by madovsky** [comment]
well Rinat, you just rock :)
now maybe it's worth to teach google developers to include this patch since chrome can't see the loopback at all :)

**Comment by i-rinat** [comment]
> chrome can't see the loopback at all

Works on my machine. And `strace` also shows that it probes all `video*` devices in `/dev`.

Have you tested loopback itself? I've only succeeded with piping real webcam into loopback device with help of `gst-launch`. Other examples don't work for me.

**Comment by madovsky** [comment]
firefox and seamonkey shows well now, but not chrome at all yes.
ok I think I understand why. maybe chrome asks a real stream and not an image streamed....
going to try now

**Comment by madovsky** [comment]
Could you provide the gst-launch command line you used to make it work on chrome?
I still can't use my loopback device on it thanks

**Comment by i-rinat** [comment]
I first found that
```
gst-launch-1.0 v4l2src device=/dev/video0 ! videorate ! v4l2sink device=/dev/video1
```
works fine. And `videorate` was somehow important, it didn't work without it. But now I tried just
```
gst-launch-1.0 v4l2src device=/dev/video0 ! v4l2sink device=/dev/video1
```
and it also worked fine.

**Comment by madovsky** [comment]
I could start a stream with gst-launch -v ximagesrc startx=0 starty=0 endx=1920 endy=1200 ! ffmpegcolorspace ! "video/x-raw-yuv,width=1920,height=1200,framerate=5/1" ! v4l2sink device=/dev/video1
on Fedora 23, your command showed  flow error.
anyhow even if I can see video 1 on device list on flash player in all browsers, impossible to make it work on Chrome. it does not see any video device :(

**Comment by madovsky** [comment]
btw Rinat, here is the discussion about chrome and V4l2loopback and why on my side I couldn't see it on the device list
https://github.com/umlaeute/v4l2loopback/issues/40
